version: "3.3"

services:
  app:
    container_name: 'app'
    build: .
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./package.json:/app/package.json
      - ./yarn.lock:/app/yarn.lock
      - db-data:/app/db
    ports:
      - 4000:4000

volumes:
  db-data: